export const Skill_set = [
  {
    skill_name: 'Illustrator',
    Image: '/ai.webp',
    width: 60,
    height: 60,
  },
  {
    skill_name: 'Figma',
    Image: '/figma.webp',
    width: 50,
    height: 50,
    style: 4,
  },
  {
    skill_name: 'Photoshop',
    Image: '/ps.webp',
    width: 60,
    height: 60,
    style: 4,
  },
  {
    skill_name: 'Adobe Xd',
    Image: '/xd.webp',
    width: 55,
    height: 55,
    style: 4,
  },
  {
    skill_name: 'WireFrame',
    Image: '/wireframe.webp',
    width: 55,
    height: 55,
    style: 4,
  },
  {
    skill_name: 'UX',
    Image: '/user experience.webp',
    width: 55,
    height: 55,
    style: 4,
  },
  {
    skill_name: 'UX Design',
    Image: '/user experience design.webp',
    width: 60,
    height: 60,
    style: 4,
  },
  {
    skill_name: 'Prototyping',
    Image: '/prototyping.webp',
    width: 55,
    height: 55,
    style: 4,
  },
  {
    skill_name: 'User Research',
    Image: '/user research.webp',
    width: 55,
    height: 55,
    style: 4,
  },
]
